import type { HouseSpec } from '../house';
import { desk, tableSet } from '../furniture';

/** Escritório modelo: 4 salas + corredor, no estilo dollhouse 2.5D. Ver docs/houses/AUTHORING.md. */

export const OFFICE_HOUSE: HouseSpec = {
  id: 'office',
  mapCols: 48,
  mapRows: 38,
  spawn: { col: 22, row: 18 },
  rooms: [
    {
      id: 'office',
      name: 'Open Office',
      x: 5,
      y: 5,
      w: 17,
      h: 9,
      floor: 'floor-office',
      wallpaper: 'wall-farm',
    },
    {
      id: 'meeting',
      name: 'Sala de Reunião',
      x: 23,
      y: 5,
      w: 18,
      h: 9,
      floor: 'floor-meeting',
      wallpaper: 'wall-blue',
    },
    {
      id: 'hall',
      name: 'Corredor',
      x: 5,
      y: 17,
      w: 36,
      h: 3,
      floor: 'floor-hall',
      wallpaper: 'wall-plank',
    },
    {
      id: 'lounge',
      name: 'Lounge',
      x: 5,
      y: 23,
      w: 17,
      h: 8,
      floor: 'floor-lounge',
      wallpaper: 'wall-red',
    },
    {
      id: 'cafe',
      name: 'Café',
      x: 23,
      y: 23,
      w: 18,
      h: 8,
      floor: 'floor-cafe',
      wallpaper: 'wall-wood',
    },
  ],
  doors: [
    { x: 22, y: 7, w: 1, h: 3 },
    { x: 22, y: 25, w: 1, h: 3 },
  ],
  stairs: [
    { x: 8, y: 14, w: 5, h: 3 },
    { x: 32, y: 14, w: 5, h: 3 },
    { x: 8, y: 20, w: 5, h: 3 },
    { x: 32, y: 20, w: 5, h: 3 },
  ],
  furniture: [
    ...desk(7, 6),
    ...desk(13, 6),
    ...desk(19, 6),
    ...desk(7, 10),
    ...desk(13, 10),
    ...desk(19, 10),
    { item: 'bookshelf', col: 5, row: 5 },
    { item: 'plant', col: 21, row: 8 },
    { item: 'plant-fern', col: 21, row: 13 },

    { item: 'cabinet', col: 24, row: 5 },
    { item: 'bookshelf-light', col: 27, row: 5 },
    { item: 'bookshelf', col: 38, row: 5 },
    { item: 'plant-fern', col: 24, row: 12 },
    { item: 'plant', col: 40, row: 12 },
    { item: 'rug', col: 29, row: 9 },
    ...tableSet(30, 8),

    { item: 'tv', col: 14, row: 23 },
    { item: 'sofa', col: 7, row: 26 },
    { item: 'sofa', col: 15, row: 26 },
    { item: 'armchair', col: 6, row: 29 },
    { item: 'armchair', col: 17, row: 29 },
    { item: 'rug', col: 10, row: 26 },
    { item: 'plant', col: 5, row: 23 },
    { item: 'plant-fern', col: 20, row: 23 },

    { item: 'fridge', col: 24, row: 23 },
    { item: 'stove', col: 25, row: 23 },
    { item: 'sink', col: 26, row: 23 },
    { item: 'counter', col: 27, row: 23 },
    ...tableSet(34, 27),
    { item: 'plant', col: 40, row: 30 },
  ],
};
